services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./FilmsCatalog:/FilmsCatalog
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=dbpassword

    command: >
      sh -c "python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database


  database:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword